### ISSUE TITLE
dir/ls: get list of files and folders

### ISSUE THREAD

**Issue by wendydv1989** [jmozah/intOS-dfs#34]
![image](https://user-images.githubusercontent.com/52613476/91661737-26093b80-eade-11ea-98b9-28df2531b947.png)

I would like to get a list back of files and folders for a specific path. 

Fi: 
give me path /Pictures

contents = [
        { title: "Documents", icon: "folder" },
        { title: "Pictures", icon: "folder" },
        { title: "Movies", icon: "folder" },
        { title: "DappConnect", icon: "folder" },
        { title: "Shared", icon: "folder" },
        { title: "Keith Jarret - Koln Concert Extra long title.mp3", icon: "mp3" },
        { title: "HelloWorld.txt", icon: "txt" },
        { title: "MyAvatar.png", icon: "sad" },
        { title: "BBC.Documentary.mp4", icon: "asdasd" },
    ]

**Comment by jmozah** [comment]
Branch Create_user hash a95b7d43d65199475669c9f88e15115b4faa15c4 has this fixed.
