### ISSUE TITLE
Create basic UI

### ISSUE THREAD

**Issue by jmozah** [jmozah/intOS-dfs#6]
For now dfs only has a command line interface, This issue is about adding a basic UI to dfs so that all the functions can be done from the UI itself.

**Comment by wendydv1989** [comment]
I suggest to do this in a new repo?

**Comment by jmozah** [comment]
This is a just a plain html template to test the api. The actual full fledged UI should be in a separate repo. See this https://github.com/jmozah/intOS-dfs/pull/5/files#diff-0978caee85fe0c187eb4ae5f8952d547

**Comment by jmozah** [comment]
Closing this as this is Not required. API should be tested using some external rest client like Postman.
