### ISSUE TITLE
Handle situation when bee not running when creating user

### ISSUE THREAD

**Issue by crtahlin** [jmozah/intOS-dfs#68]
i created a new user, but got: 

"create user:  create name feed: Post http://127.0.0.1:8080/chunks/f9a06b547f10c4f60aefe7b04b22b91fa1303e96794ec0cff7529ccbbb469ee6: dial tcp 127.0.0.1:8080: connect: connection refused
"

i guess since bee was not running. the user was created anyway. but i'm now in some sort of strange situation:

![image](https://user-images.githubusercontent.com/1554520/93074426-a1452280-f684-11ea-9cd4-4b65bb818f91.png)

i guess due to the feed not being created?

i would expect a rollback of user creating if the feed fails; or creating the feed on the next attempt

**Comment by crtahlin** [comment]
See also comment in code: https://github.com/jmozah/intOS-dfs/blob/master/pkg/dfs/api.go#L61

**Comment by jmozah** [comment]
Fixed in commit 1a9cee814877cb525e9728b991ad25bbbbc5787c

**Comment by crtahlin** [comment]
verified, error returned when bee not running
