### ISSUE TITLE
Correct wording when opening existing pod

### ISSUE THREAD

**Issue by crtahlin** [jmozah/intOS-dfs#70]
![image](https://user-images.githubusercontent.com/1554520/93132488-05dc9d80-f6d6-11ea-83c8-2d08d0ee70a2.png)

Should say "to open", not "to create" (since it already exists).

**Comment by jmozah** [comment]
fixed in commit b4498ae4465d0f228dda5e3a37028db90b4becca

**Comment by crtahlin** [comment]
verified
