### ISSUE TITLE
User present should return true / false

### ISSUE THREAD

**Issue by crtahlin** [jmozah/intOS-dfs#71]
![image](https://user-images.githubusercontent.com/1554520/93132776-813e4f00-f6d6-11ea-81c6-df2b3f5be539.png)

While it now returns available / not available, which is counter to the help description. 

A note: it might be better if the output in REPL is "user present" / "user not present", because true/false and available/not available is maybe somewhat confusing, at least to me. 
or at least:
"User present: true"

Currently, it says "user name available", which could be understood that such a user does not exist, hence the name is available.

**Comment by jmozah** [comment]
Fixed in commit  5f84f4ecc302485f13d57b8af34f6655e5f981c4

**Comment by crtahlin** [comment]
verified - true/ false is returned.
