### ISSUE TITLE
CheckShareId > api for getting details on a shareId

### ISSUE THREAD

**Issue by wendydv1989** [jmozah/intOS-dfs#74]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when my GF has a headache [...]

**Describe the solution you'd like**
url: /file/shareIdCheck/<shareId>

return: { fileName: string,
fileSize: number, 
fileType: mimeString,
shareUser: optional string,
shareAvatar: optional string,
fileShared: timestamp of sharemoment}

**Describe alternatives you've considered**

**Additional context**

**Comment by jmozah** [comment]
fixed in commit 3b09d675db1b2268859969c8552d04694ceb50bf
