### ISSUE TITLE
User name directory in Swarm

### ISSUE THREAD

**Issue by jmozah** [jmozah/intOS-dfs#80]
- should store user name and related details in swarm
- if a new user is created, it should be check with the existing user name to see if it is present or not
- i should be able to search for user name

**Comment by wendydv1989** [comment]
Can we talk about this
I’m hesitant to keep a user dir

**Comment by jmozah** [comment]
- user name to address mapping still in local dfs store
- encrypted mnemonic is pushed to swarm for easy user export and import
