### ISSUE TITLE
Add checking if dir already exists

### ISSUE THREAD

**Issue by crtahlin** [jmozah/intOS-dfs#81]
Currently, I can `mkdir dir1` and if the dir already exists, no message is returned. I would expect sth like "Directory already exists."
Although not sure if only cosmetic, but would improve the UI, I think. 

![image](https://user-images.githubusercontent.com/1554520/93293904-67d9f780-f7e9-11ea-8ba6-06699403760b.png)

**Comment by jmozah** [comment]
fixed by the commit 4c0174e4188bb76fccffa426d72e96496adfead2
